{{- if not .Values.config.secrets.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: oss-catalog-secrets
  labels:
    {{- include "oss-catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.config.secrets.githubToken }}
  api-bearer-token: {{ .Values.config.secrets.apiBearerToken }}
  pasetoKey: {{ .Values.config.secrets.pasetoKey }}
  databaseDSN: {{ .Values.config.secrets.databaseDSN }}
{{- end }}